name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Build Frontend
        run: |
          cd web-frontend
          npm install
          npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: web-frontend-build
          path: web-frontend/build/

  build-backend:
    runs-on: ubuntu-latest
    needs: build-frontend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - uses: actions/download-artifact@v2
        with:
          name: web-frontend-build
          path: backend/src/main/resources/static
      - name: Build with maven
        env:
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME}}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          SMTP_SERVER:  ${{ secrets.SMTP_SERVER }}
        run: mvn -B package --file backend/pom.xml
      - uses: actions/upload-artifact@v2
        with:
          name: app.jar
          path: backend/target/app.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build-backend
    environment:
      name: production-fly
      url: https://biokiste.fly.dev/
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_IO_API_KEY }}
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - uses: actions/download-artifact@v2
        with:
          name: app.jar
          path: backend/target
      - run: flyctl deploy --remote-only
